CREATE TABLE IF NOT EXISTS post (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    uuid VARCHAR(255) UNIQUE NOT NULL,
    creator_uuid VARCHAR(255) NOT NULL,
    headline VARCHAR(255) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    preview_img BLOB,
    content BLOB NOT NULL,
    is_protected BOOLEAN DEFAULT FALSE,

    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;